import { Word } from "./word";

export const WORDS: Word[] = [
  { word: 'wstrętny', translation: 'противный'},
  { word: 'zdolny', translation: 'способный'},
  { word: 'wysmukły', translation: 'подтянутый'},
  { word: 'źrenice', translation: 'зрачки'},
  { word: 'rzęsy', translation: 'ресницы'},
  { word: 'sprzedawać', translation: 'продавать'},
  { word: 'łączyć', translation: 'соединять'},
  { word: 'Ciśnienie', translation: 'давление'},
  { word: 'Gardło', translation: 'горло'},
  { word: 'Uczulenie', translation: 'аллергия'},
  { word: 'stopni Celsjusza', translation: 'градусов Цельсия'},
  { word: 'Ubezpieczenie', translation: 'страховка'},
  { word: 'Obcokrajowiec', translation: 'Иностранец'},
  { word: 'Rozwijać się', translation: 'развиваться'},
  { word: 'Wspierać', translation: 'поддерживать'},
  { word: 'Mieć kaca', translation: 'иметь будун'},
  { word: 'Nawilżyć', translation: 'увлажнить'},
  { word: 'Nerki', translation: 'почки'},
  { word: 'Wątroba', translation: 'печень'},
  { word: 'Płuca', translation: 'легкие'},
  { word: 'Serce', translation: 'сердце'}, 
  { word: 'Zmęczony', translation: 'уставший'},
  { word: 'Mieć zawroty głowy', translation: 'кружится в голове'},
  { word: 'Wymiotować', translation: 'блевать'},
  { word: 'Mieć nudności', translation: ' тошнить'},
  { word: 'Biegunka', translation: 'понос'},
  { word: 'Mieć temperaturę(gorączkę)', translation: 'Температура/жар'},
  { word: 'Mieć dreszcze', translation: 'озноб'},
  { word: 'Kichać', translation: 'чихать'},
  { word: 'Kaszleć', translation: 'кашлять'},
  { word: 'Katar = zatkany nos', translation: 'насморк'},
  { word: 'Przeziębienie', translation: 'простуда'},
  { word: 'Jakość', translation: 'качество'},
  { word: 'Chorować', translation: 'болеть'},
  { word: 'Punkt widzenia', translation: 'точка зрения'},
  { word: 'Ogólnie', translation: 'вообще'},
  { word: 'Starać się', translation: 'пытаться'},
  { word: 'Zrezygnować z', translation: 'отказаться от '},
  { word: 'Stosować dietę', translation: 'соблюдать диету'},
  { word: 'Robić brzuszki', translation: 'качать прес'},
  { word: 'Robić przysiady', translation: 'приседать'},
  { word: 'Robić pompki', translation: 'отжиматься'},
  { word: 'Biegać', translation: 'бегать'},
  { word: 'Zawierać', translation: 'иметь в составе'},
  { word: 'Węglowodany', translation: 'углеводы'},
  { word: 'Tłuszcze', translation: 'жиры'},
  { word: 'Białko', translation: ' белки'},
  { word: 'Wysiłek fizyczny', translation: 'физическая нагрузка '},
  { word: 'Odchudzać się', translation: 'худеть'},
  { word: 'Niedobór wagi ', translation: 'дефицит веса'},
  { word: 'Nadwaga', translation: 'слишком большой вес'},
  { word: 'Otyłość', translation: 'ожирение'},
  { word: 'Tyć ', translation: 'поправляться'},
  { word: 'Zmarszczki', translation: 'морщины'},
  { word: 'Potylica', translation: 'затылок'},
  { word: 'Okropny', translation: 'ужасный'},
  { word: 'Czasami', translation: 'иногда'},
  { word: 'Cienki', translation: 'тонкий'},
  { word: 'Olśniewająco', translation: 'умопомрачительно'},
  { word: 'Wyglądać bosko', translation: 'Выглядеть божественно'},
  { word: 'dzieci', translation: 'дети'},
  { word: 'Wyjątek', translation: 'Исключение'},
  { word: 'Żaden', translation: 'никакой'},
  { word: 'Ciuchy', translation: 'шмотки'},
  { word: 'Ostrzyżone', translation: 'обрезаные'},
  { word: 'Krótkie', translation: 'короткие'},
  { word: 'Zadbany', translation: 'ухоженный'},
  { word: 'Obcisłe spodnie', translation: 'Узкие брюки'},
  { word: 'Luźne spodnie', translation: ' свободные штаны'},
  { word: 'Luz', translation: 'расслабон'},
  { word: 'Wyluzować', translation: 'расслабится'},
  { word: 'Wyjść za mąż', translation: 'выйти за муж'},
  { word: 'Ożenić', translation: 'женится'},
  { word: 'Szczęście', translation: 'счастье'},
  { word: 'Wpływać', translation: 'влиять'},
  { word: 'Przez to , że', translation: 'изза того, что'},
  { word: 'Wcześniej', translation: 'раньше'},
  { word: 'Zwracać uwagę', translation: ' обращать внимание'},
  { word: 'Kojarzyć', translation: 'ассоциировать'},
  { word: 'Zostawiać', translation: 'оставлять'},
  { word: 'wszystko jedno', translation: 'все ровно'},
  { word: 'obojętnie', translation: 'все ровно'},
  { word: 'dobry pomyśł', translation: 'хорошая мысль/ идея'},
  { word: 'nie mam pojęcia', translation: 'не имею понятия'},
  { word: 'moim zdaniem', translation: 'на мою думку'},
  { word: 'irytować', translation: 'раздражать'},
  { word: 'pada śnieg', translation: 'идет снег'},
  { word: 'pada deszcz', translation: 'идет дождь'},
  { word: 'mgła', translation: 'туман'},
  { word: 'ktokolwiek', translation: 'кто -небудь'},
  { word: 'przerywać', translation: 'перебивать'},
  { word: 'okres', translation: 'период/менструация'},
  { word: 'miesiączka', translation: 'менструация'},
  { word: 'w końcu', translation: 'в конце концов'},
  { word: 'wątpić', translation: 'сомневатся'},
  { word: 'tu =tutaj', translation: 'здесь'},
  { word: 'troska', translation: 'турбота'},
  { word: 'obudzić się', translation: 'проснутся'},
  { word: 'wspominać', translation: 'вспоминать'},
  { word: 'pod czas', translation: 'во время'},
  { word: 'Wigilia', translation: 'сочельник'},
  { word: 'być zaskoczonym', translation: 'быть в шоке'},
  { word: 'nie mieć nic przeciwko', translation: 'не иметь ничего против'},
  { word: 'zdziwić się', translation: 'удивить'},
  { word: 'zgodzić się', translation: 'согласится'},
  { word: 'podrzucić', translation: 'подбросить'},
  { word: 'podwieźć', translation: 'подвезти'},
  { word: 'drożdżówka', translation: 'сладкая булочку'},
  { word: 'zapłacić', translation: 'заплатить'},
  { word: 'mężczyzna', translation: 'мужчина'},
  { word: 'stacja tankowania', translation: 'заправка'},
  { word: 'zobaczyć', translation: 'увидеть'},
  { word: 'przepraszać(kogo? co?)', translation: 'извинять'},
  { word: 'rzucić', translation: 'бросить'},
  { word: '10 deka', translation: '100 gram'},
  { word: 'najpierw', translation: 'сначала'},
  { word: 'zapoznać się z', translation: 'познакомится с'},
  { word: 'poznać', translation: 'познакомится'},
  { word: 'spotkać', translation: 'встретить'},
  { word: 'dalej', translation: 'следующий'},
  { word: 'następnie', translation: 'затем'},
  { word: 'przede wszystkim', translation: 'прежде всего'},
  { word: 'polecieć', translation: 'полететь'},
  { word: 'niespodzianka', translation: 'сюрприз'},
  { word: 'już', translation: 'уже'},
  { word: 'Gry planszowe', translation: 'настильные игры'},
  { word: 'obchodzić', translation: 'праздновать'},
  { word: 'zaprosić', translation: 'пригласить'},
  { word: 'zapraszać', translation: 'приглашать'},
  { word: 'podziwiać', translation: 'любоваться'},
  { word: 'szukać', translation: 'искать'},
  { word: 'inna', translation: 'другая'},
  { word: 'widać', translation: 'Видно'},
  { word: 'żonaty', translation: 'женат'},
  { word: 'prawie', translation: 'почти'},
  { word: 'historia', translation: 'история'},
  { word: 'Boże narodzenie', translation: 'Рождество'},
  { word: 'muszka', translation: 'бабочка'},
  { word: 'Zegarek', translation: 'часы ( на руке)'},
  { word: 'zegar', translation: 'часы'},
  { word: 'Zakładać', translation: 'одевать'},
  { word: 'Prąd', translation: 'электричество'},
  { word: 'Polecać', translation: 'советовать'},
  { word: 'Przeprowadzać się', translation: 'переезжать'},
  { word: 'Wycierać', translation: 'вытирать'},
  { word: 'Większy', translation: 'больший'},
  { word: 'przeszkadzać', translation: 'мешать'},
  { word: 'wściekła', translation: 'очень зла'},
  { word: 'gwiazdу', translation: 'звёзды'},
  { word: 'łyżwy', translation: 'коньки'},
  { word: 'narty', translation: 'лыжи'},
  { word: 'róg', translation: 'угол'},
  { word: ' w rogu', translation: 'на углу'},
  { word: 'naprzeciwko', translation: 'напротив'},
  { word: 'szampon', translation: 'Шампунь'},
  { word: 'ręcznik', translation: 'полотенце'},
  { word: 'ekspres do kawy', translation: 'кофе машина'},
  { word: 'naczynia', translation: 'посуда'},
  { word: 'marzyć', translation: 'мечтать'},
  { word: 'zbędne', translation: 'лишнее'},
  { word: 'czynsz', translation: 'коммуналка'},
  { word: 'wady', translation: 'недостатки'},
  { word: 'zalety', translation: 'преимущества'},
  { word: 'Dywan', translation: 'коврик'},
  { word: 'Ubikacja', translation: 'туалет'},
  { word: 'Kwiatek', translation: 'цветок'},
  { word: 'Zmywarka', translation: 'посудомойка'},
  { word: 'Kuchenka', translation: 'плита'},
  { word: 'Krzesło', translation: 'стул'},
  { word: 'Lustro', translation: 'зеркало'},
  { word: 'Prysznic', translation: 'душ'},
  { word: 'Fotel', translation: 'мягкое кресло'},
  { word: 'Pralka', translation: 'стиралка'},
  { word: 'Sofa', translation: 'диван'},
  { word: 'Lodówka', translation: 'холодильник'},
  { word: 'komunikacja miejska', translation: 'инфраструктура'},
  { word: 'obok', translation: 'возле'},
  { word: 'piekło', translation: 'ад'},
  { word: 'potrawa', translation: 'блюдо'},
  { word: 'powietrze', translation: 'воздух'},
  { word: 'zimne', translation: 'холодное'},
  { word: 'prawie', translation: 'почти'},
  { word: 'znajdować się', translation: 'находится'},
  { word: 'dworzec', translation: 'вокзал'},
  { word: 'naprzeciwko', translation: 'напротив'},
  { word: 'na dole', translation: 'снизу'},
  { word: 'na górze', translation: 'сверху'},
  { word: 'skręcać', translation: 'поворачивать'},
  { word: 'skręcić', translation: 'свернуть'},
  { word: 'z tyłu', translation: 'сзади'},
  { word: 'do tyłu', translation: 'назад'},
  { word: 'na zewnątrz', translation: 'снаружи'},
  { word: 'nawet', translation: 'даже'},
  { word: 'w poszukiwaniu', translation: 'в поисках'},
  { word: 'artysta', translation: 'художник'},
  { word: 'obrazy', translation: 'картины'},
  { word: 'słychać', translation: 'слышно'},
  { word: 'widać', translation: 'видно'},
  { word: 'gdziekolwiek', translation: 'где небудь'},
  { word: 'duży', translation: 'большой'},
  { word: 'dużo', translation: 'много'},
  { word: 'zwiedzać', translation: 'посещать'},
  { word: 'zwiedzić', translation: 'посетить'},
  { word: 'skrzyżowanie', translation: 'перекресток'},
  { word: 'przystanek', translation: 'остановка'},
  { word: 'dzielnica', translation: ' район (города)'},
  { word: 'przerywać', translation: 'перебивать'},
  { word: 'przewodnik', translation: 'экскурсовод'},
  { word: 'postanowić', translation: 'решить'},
  { word: 'piosenka', translation: 'песня'},
  { word: 'szpital', translation: 'больница'},
  { word: 'W tym roku', translation: 'в этом году'},
  { word: 'Obchodzić', translation: 'праздновать'},
  { word: 'świętować', translation: 'праздновать'},
  { word: 'Powiedzieć', translation: 'сказать'},
  { word: 'Wynająć', translation: 'снять (квартиру)'},
  { word: 'Zająć', translation: 'занять'},
  { word: 'Zrobić porządek', translation: 'убраться'},
  { word: 'posprzątać', translation: 'убирать'},
  { word: 'Zatrudnić się', translation: 'устроится (на роботу)'},
  { word: 'Zapłacić', translation: 'заплатить'},
  { word: 'Płacić', translation: 'платить'},
  { word: 'Wykształcenie', translation: 'образование'},
  { word: 'Wykształcony', translation: 'образованный'},
  { word: 'Sprawdzić', translation: 'проверить'},
  { word: 'Sprawdzać', translation: 'проверять'},
  { word: 'Pakować walizy', translation: 'собирать чемоданы'},
  { word: 'Zabytki = miejsca zabytkowe', translation: 'памятные места'},
  { word: 'Konsola', translation: 'Плейстейшн'},
  { word: 'Żydzi', translation: 'евреи'},
  { word: 'Bilet', translation: 'билет'},
  { word: 'cukini', translation: 'Кабачок'},
  { word: 'spóźniać się', translation: 'опаздывать'},
  { word: 'lody', translation: 'мороженое'},
  { word: 'słodycze', translation: 'сладости'},
  { word: 'orzechy', translation: 'орехи'},
  { word: 'chipsy', translation: 'чипсы'},
  { word: 'przekąski', translation: 'снеки'},
  { word: 'wykształcony', translation: 'образование'},
  { word: 'kawior', translation: 'икра'},
  { word: 'różne', translation: 'разные'},
  { word: 'szaszłyk', translation: 'шашлык'},
  { word: 'ilość', translation: 'количество'},
  { word: 'okres', translation: 'период'},
  { word: 'dlatego', translation: 'поэтому'},
  { word: 'można', translation: 'можно'},
  { word: 'wtedy', translation: 'тогда'},
  { word: 'wrócić', translation: 'вернутся'},
  { word: 'zacząć', translation: 'начать'},
  { word: 'dołączyć', translation: 'присоеденится'},
  { word: 'Pociąg', translation: 'поезд'},
  { word: 'Poziomki', translation: 'земляника'},
  { word: 'Kąpać się', translation: 'купаться'},
  { word: 'Pływać', translation: 'плавать'},
  { word: 'Opalać się', translation: 'загорать'},
  { word: 'Jezioro', translation: 'озеро'},
  { word: 'Piłka nożna', translation: 'футбол'},
  { word: 'Koszykówka', translation: 'баскетбол'},
  { word: 'Siatkówka', translation: 'волейбол'},
  { word: 'Wycieczka', translation: 'экскурсия'},
  { word: 'Odpoczywać', translation: 'отдыхать'},
  { word: 'Gdzie', translation: 'где'},
  { word: 'Na imprezę', translation: 'на вечеринку'},
  { word: 'W goście', translation: 'в гости'},
  { word: 'Spotkanie', translation: 'встреча'},
  { word: 'Porównywać', translation: 'сравнивать'},
  { word: 'tłumaczyć', translation: 'переводить, обьяснять'},
  { word: 'zmrużyć oczy', translation: 'закрыть глаза'},
  { word: 'zamknąć', translation: 'закрыть'},
  { word: 'przewracać się', translation: 'поворачиваться'},
  { word: 'kręcić się', translation: 'крутиться'},
  { word: 'natomiast', translation: 'в то время как'},
  { word: 'natychmiast', translation: 'немедленно'},
  { word: 'łóżko', translation: 'кровать'},
  { word: 'iść spacer', translation: 'идти гулять'},
  { word: 'spacerować', translation: 'гулять'},
  { word: 'patrzeć na', translation: 'смотреть на'},
  { word: 'cały dzień ', translation: 'целый день'},
  { word: 'brać urlop', translation: 'брать отпуск'},
  { word: 'urlop', translation: 'отпуск'},
  { word: 'wykłady', translation: 'лекции'},
  { word: 'pędzić', translation: 'спешить'},
  { word: 'połknąć', translation: 'проглотить'},
  { word: 'połykać', translation: 'проглатывать'},
  { word: 'spieszyć się', translation: 'спешить'},
  { word: 'szybko', translation: 'быстро'},
  { word: 'ubierać się', translation: 'одеваться'},
  { word: 'sprzątać', translation: 'убирать'},
  { word: 'rozprostować  się', translation: 'выпрямиться'},
  { word: 'wcześnie', translation: 'рано'},
  { word: 'kupować', translation: 'покупать'},
  { word: 'rano', translation: 'утром'},
  { word: 'wczoraj', translation: 'вчера'},
  { word: 'woda gazowana', translation: 'газированная вода'},
  { word: 'Burak', translation: 'свекла'},
  { word: 'Włochy', translation: 'Италия'},
  { word: 'Deser', translation: 'десерт'},
  { word: 'Pęczek', translation: 'пучок'},
  { word: 'Owszem', translation: 'конечно же'},
  { word: 'Worek', translation: 'пакетик'},
  { word: 'Podroby', translation: 'потроха'},
  { word: 'Parówki', translation: 'сосиски'},
  { word: 'Duży', translation: 'большой'},
  { word: 'Wątroba', translation: 'печень'},
  { word: 'Boczek', translation: 'бекон'},
  { word: 'Magazyn', translation: 'журнал , склад'},
  { word: 'Supermarket', translation: 'супермаркет'},
  { word: 'Galeria', translation: 'торговый центр'},
  { word: 'Sklep', translation: 'магазин'},
  { word: 'Śledź', translation: 'селедка'},
  { word: 'Dorsz', translation: 'треска'},
  { word: 'Pstrąg', translation: 'форель'},
  { word: 'Pieczarki', translation: 'шампиньоны'},
  { word: 'Węgorz', translation: 'угорь'},
  { word: 'Lód', translation: 'мороженое'},
  { word: 'Ile', translation: 'сколько'},
  { word: 'Więcej', translation: 'больше'},
  { word: 'Mniej', translation: 'меньше'},
  { word: 'Dojrzałe', translation: 'спелые'},
  { word: 'Wtedy', translation: 'тогда, в таком случае'},
  { word: 'Porównywać', translation: 'сравнивать'},
  { word: 'Ile to kosztuje ?', translation: 'Сколь это стоит ?'},
  { word: 'Płacić', translation: 'платить'},
  { word: 'Do tego wina pasuje ser', translation: 'Сыр хорошо сочетается с этим вином'},
  { word: 'Pasować', translation: 'подходить'},
  { word: 'Batoniki', translation: 'батончик'},
  { word: 'Ciasto', translation: 'пирог'},
  { word: 'Babeczki', translation: 'кексы'},
  { word: 'Herbatniki', translation: 'печенье к чаю'},
  { word: 'Ciastko', translation: 'печенье'},
  { word: 'Słodycze', translation: 'сладости'},
  { word: 'Czekolada', translation: 'шоколад'},
  { word: 'Kiszony ogórek', translation: 'квашеные огурцы'},
  { word: 'Koperek', translation: 'укроп'},
  { word: 'Pieprz', translation: 'перец(специи)'},
  { word: 'Sól', translation: 'соль'},
  { word: 'Oliwa z oliwek', translation: 'масло оливковое'},
  { word: 'Olej', translation: 'масло (подсолнечное)'},
  { word: 'Dodać', translation: 'Добавить'},
  { word: 'Kurczak', translation: 'курица'},
  { word: 'Dziczyzna', translation: 'мясо дикий зверей'},
  { word: 'Drób', translation: 'мясо птицы'},
  { word: 'Wołowina', translation: 'говядина'},
  { word: 'Wieprzowina', translation: 'свинина'},
  { word: 'ketczup', translation: 'кетчуп'},
  { word: 'musztarda', translation: 'горчица'},
  { word: 'wytrawne wino', translation: 'сухое вино'},
  { word: 'mocna kawa', translation: 'крепкий кофе'},
  { word: 'chuda kiełbasa', translation: 'не жирная колбаса'},
  { word: 'tłusta', translation: 'жирное'},
  { word: 'kolacja', translation: 'ужин'},
  { word: 'obiad', translation: 'обед'},
  { word: 'śniadanie', translation: 'завтрак'},
  { word: 'dzisiaj = dziś ', translation: 'сегодня'},
  { word: 'pukać', translation: 'стучать'},
  { word: 'mieć ochotę na', translation: 'мне хочеться'},
  { word: 'jeszcze', translation: 'еще'},
  { word: 'już', translation: 'уже'},
  { word: 'chętnie', translation: 'с удовольствие'},
  { word: 'jedzenie', translation: 'пища'},
  { word: 'głodny', translation: 'голодный'},
  { word: 'mam nadzieję', translation: 'надеюсь'},
  { word: 'blizna', translation: 'шрам'},
  { word: 'różny', translation: 'разный'},
  { word: 'Nie jestem pewny', translation: 'Я не уверен'},
  { word: 'nie wiem, czy warto', translation: 'не зна́ю, сто́ит ли?'},
  { word: 'Ja myślę , że ', translation: 'я думаю что'},
  { word: 'Ode mnie', translation: 'од меня'},
  { word: 'Piękna dziewczyna', translation: 'Красивая девушка'},
  { word: 'Piękna', translation: 'красива'},
  { word: 'Przystojny mężczyzna', translation: 'Красивый мужчина'},
  { word: 'Przystojny', translation: 'красивый'},
  { word: 'Łączyć', translation: 'соединят'},
  { word: 'Do tylu', translation: 'назад'},
  { word: 'Wycieczka', translation: 'экскурсия , поход'},
  { word: 'Plecy', translation: 'спина'},
  { word: 'Brzuch', translation: 'живот'},
  { word: 'Nadgarstek', translation: 'запястья'},
  { word: 'Ręce', translation: 'руки'},
  { word: 'Ręka prawa', translation: 'рука права'},
  { word: 'Ręka lewa', translation: 'Левая рука'},
  { word: 'Kończyny', translation: 'конечности'},
  { word: 'Policzek', translation: 'щека'},
  { word: 'policzki', translation: 'щеки'},
  { word: 'Ucho', translation: 'Ухо'},
  { word: 'uszy', translation: 'уши'},
  { word: 'Podbródek', translation: 'Подбородок'},
  { word: 'Broda', translation: 'Брода'},
  { word: 'Wargi', translation: 'Губы'},
  { word: 'Usta', translation: 'рот'},
  { word: 'Rzęsy', translation: 'ресницы'},
  { word: 'Źrenice', translation: 'зрачки'},
  { word: 'Oko', translation: 'Глаз'},
  { word: 'oczy', translation: 'глаза'},
  { word: 'Czoło', translation: 'Лоб'},
  { word: 'Twarz', translation: 'лицо (rodzaj żeński)'},
  { word: 'Długie', translation: 'длинные'},
  { word: 'Wszystko dobrze', translation: 'все хорошо'},
  { word: 'Wysportowany', translation: 'спортивный'},
  { word: 'Wysmukły', translation: 'подтянутый'},
  { word: 'Szczupły', translation: 'худой'},
  { word: 'Proste', translation: 'прямые'},
  { word: 'Kręcone', translation: 'кучерявые'},
  { word: 'Piwne', translation: 'карие'},
  { word: 'Opinia', translation: 'мнение'},
  { word: 'Roztargniony', translation: 'Рассеянный'},
  { word: 'Powolny', translation: 'медленный'},
  { word: 'Myślący', translation: 'думающий'},
  { word: 'Zdolny', translation: 'способный'},
  { word: 'Wstrętny', translation: 'противный'},
  { word: 'Uczynny', translation: 'услужливый,честный'},
  { word: 'Dziennikarz', translation: 'журналист'},
  { word: 'Sprzedawać', translation: 'продавать'},
  { word: 'Dosłuchiwać się', translation: 'дослушаться'},
  { word: 'Domyślać się', translation: 'додумыватся'},
  { word: 'Myśleć', translation: 'думать'},
  { word: 'Gadać', translation: 'говорить,болтать'},
  { word: 'Dogadywać się', translation: 'договариваться'},
  { word: 'Rozwiązywać', translation: 'подвязывать'},
  { word: 'Leczyć ludzi', translation: 'лечить людей'},
  { word: 'Zostać', translation: 'стать'},
  { word: 'Podróż', translation: 'путешествие'},
  { word: 'Spełnić marzenie', translation: 'осуществить мечту'},
  { word: 'Prawnik', translation: 'юрист,адвокат'},
  { word: 'Księgowy', translation: 'бухгалтер'},
  { word: 'Że', translation: 'что (в средине предложения)'},
  { word: 'Jeszcze', translation: 'ещё'},
  { word: 'Gotować', translation: 'готовить'},
  { word: 'Trudny', translation: 'сложный'},
  { word: 'Sztuka współczesna', translation: 'современное искусство'},
  { word: 'Fascynować się', translation: 'восхищаться'},
  { word: 'Słuchać muzyki', translation: 'слушать  музыку'},
  { word: 'Uprawiać sport', translation: 'заниматься спортом'},
  { word: 'Uprawiać', translation: 'заниматься'},
  { word: 'Prowadzić interes', translation: 'вести бизнес'},
  { word: 'Lokal', translation: 'заведение'},
  { word: 'Przedsiębiorstwo', translation: 'частное предпринимательство'},
  { word: 'Zawód', translation: 'профессия'},
  { word: 'Na uniwersytecie', translation: 'в университете'},
  { word: 'Nastolatek', translation: 'подросток'},
  { word: 'Wieś', translation: 'деревня'},
  { word: 'Miejsce', translation: 'место'},
  { word: 'Miasto', translation: 'город'},
  { word: 'Jeść', translation: 'есть'},
  { word: 'Widzieć', translation: 'видеть'},
  { word: 'Wiedzieć', translation: 'знать'},
  { word: 'Śmieć', translation: 'сметь'},
  { word: 'Szary', translation: 'серый'},
  { word: 'Brązowy', translation: 'коричневый'},
  { word: 'Granatowy', translation: 'синий'},
  { word: 'Książka', translation: 'книжка'},
  { word: 'Zdanie', translation: 'предложение'},
  { word: 'Kiedy', translation: 'когда'},
  { word: 'Segregator', translation: 'папка'},
  { word: 'Świat', translation: 'мир'},
  { word: 'Torebka', translation: 'сумочка'},
  { word: 'Torba', translation: 'сумка,пакет'},
  { word: 'Komórka', translation: 'Ячейка /клетка /чулан'},
  { word: 'Kubek', translation: 'чашка'},
  { word: 'Biurko', translation: ' стол (письменный)'},
  { word: 'Stó', translation: 'стол'},
  { word: 'Długopis', translation: 'ручка'},
  { word: 'Ołówek', translation: 'карандаш'},
  { word: 'Dentystka', translation: 'стоматолог'},
  { word: 'Dentysta', translation: 'стоматолог'},
  { word: 'Rzeka', translation: 'река'},
  { word: 'Zdjęcie', translation: 'фотография'},
  { word: 'Żeby', translation: 'чтобы'},
  { word: 'Dlaczego', translation: ' почему'},
  { word: 'Bo= ponieważ= dlatego że', translation: 'потому что'},
  { word: 'Czesać się', translation: 'расчёсывать'},
  { word: 'Śmiać się', translation: 'смеяться'},
  { word: 'Spać', translation: 'спать'},
  { word: 'Płakać', translation: 'плакать'},
  { word: 'Pisać', translation: 'писать'},
  { word: 'Bać się', translation: 'бояться'},
  { word: 'Stać', translation: 'стоять'},
  { word: 'Prać', translation: 'стирать'},
  { word: 'Brać', translation: 'брать'},
  { word: 'Jechać', translation: 'ехать'},
  { word: 'Dziecko', translation: 'ребёнок'},
  { word: 'Państwo', translation: 'мужчины + женщины'},
  { word: 'Panie', translation: 'женщины'},
  { word: 'Panowie', translation: 'мужчины'},
  { word: 'Fatalnie', translation: 'ужасно'},
  { word: 'Źle', translation: 'плохо'},
  { word: 'W porządku', translation: 'в порядке'},
  { word: 'Dobrze', translation: 'хорошо'},
  { word: 'Świetnie', translation: 'прекрасно'},
  { word: 'Wszystko', translation: 'все'},
  { word: 'Skąd', translation: 'откуда'},
  { word: 'Twój', translation: 'твой'},
  { word: 'Mój numer', translation: 'мой номер'},
  { word: 'Jaki masz numer telefon?', translation: 'Какой у вас номер телефона?'},
  { word: 'Mam pytanie', translation: 'у меня вопрос'},
  { word: 'Że', translation: 'что(в предложении)'},
  { word: 'Co', translation: 'что'},
  { word: 'Co to znaczy?', translation: 'Что это значит'},
  { word: 'Nie rozumiem', translation: 'не понимаю'},
  { word: 'Nie wiem', translation: 'не знаю'},
  { word: 'Dziękuję = dzięki', translation: 'спасибо'},
  { word: 'Proszę', translation: 'прошу , пожалуйста'},
  { word: 'Gdzie', translation: 'Где , куда'},
  { word: 'Przepraszam', translation: 'извините'},
  { word: 'Dzień', translation: 'день'},
  { word: 'Skomplikowane', translation: 'сложное'},
  { word: 'Przedstawić się', translation: 'представится'},
  { word: 'Proszę powtórzyć', translation: 'Прошу повторит'},
  { word: 'Jutro', translation: 'завтра'},
  { word: 'Bardzo', translation: 'очень, сильно'},
  { word: 'Również=też', translation: 'тоже'},
  { word: 'Miło mi', translation: 'мне приятно'},
  { word: 'Mnie również', translation: 'мне тоже'},
  { word: 'Bardzo mi miło', translation: 'мне очень приятно'},
  { word: 'Dziadek', translation: 'дедушка'},
  { word: 'Babcia', translation: 'бабушка'},
  { word: 'Matka', translation: 'мать'},
  { word: 'Mama', translation: 'Мама'},
  { word: 'Tata', translation: 'папа'},
  { word: 'Ojciec', translation: 'отец'},
  { word: 'Siostra', translation: 'Сестра'},
  { word: 'Moja rodzina', translation: 'моя семья'},
  { word: 'Chcę opowiedzieć o', translation: 'я хочу рассказать про'},
  { word: 'Chcę', translation: 'я хочу'},
  { word: 'Spędzać', translation: 'проводить (время)'},
  { word: 'Rzecz', translation: 'вещь'},
  { word: 'obchodzić', translation: 'праздновать'},
  { word: 'następny', translation: 'следующий'},
  { word: 'dostać', translation: 'получить'},
  { word: 'zabić', translation: 'убить'},
  { word: 'blizna', translation: 'шрам'},
  { word: 'piorun', translation: 'молния'},
  { word: 'kształt', translation: 'форма'},
  { word: 'wujek', translation: 'дядя'},
  { word: 'przeprowadzić się', translation: 'переехать'},
  { word: 'przeprowadzać się', translation: 'переезжать'},
  { word: 'łódź', translation: 'лодка'},
  { word: 'znęcać się', translation: 'издеваться'},
  { word: 'przeciętny', translation: 'посредственный'},
  { word: 'kujonek', translation: 'зубрилка'},
  { word: 'wierzyć', translation: 'верить'},
  { word: 'trafić', translation: 'попасть'},
  { word: 'rzeczywistość', translation: 'реальность'},
  { word: 'śmierć', translation: 'смерть'},
  { word: 'wpłynąć', translation: 'влиять'},
  { word: 'zbyt', translation: 'слишком'},
  { word: 'obecnie', translation: 'сейчас (в данный промежуток времени)'},
  { word: 'często', translation: 'часто'},
  { word: 'rodzeństwo', translation: 'брат + сестра'},
  { word: 'małżeństwo', translation: 'супружеская пара'},
  { word: 'palić', translation: 'курить'},
 
];